zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka1:
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_CREATE_TOPICS: "${KAFKA_TOPICS}"
    KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka2:
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka3:
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
devshell:
  image: cjonesy/docker-spark:alpine
  working_dir: /spark
  environment:
    KAFKA1_HOST: kafka1
    KAFKA1_PORT: 9092
    KAFKA2_HOST: kafka2
    KAFKA2_PORT: 9092
    KAFKA3_HOST: kafka3
    KAFKA3_PORT: 9092
    ZK: zk:2181
    ZK_HOST: zk
    ZK_PORT: 2181
  volumes:
    - ./:/spark
  links:
    - zookeeper:zk
    - kafka1
    - kafka2
    - kafka3
